### ISSUE TITLE
顶部导航栏未垂直居中

### ISSUE THREAD

**Issue by swzyt** [niunai2016/ReactNativeAppDemo#1]

**Comment by swzyt** [comment]
文字会被通知栏遮挡，应该怎么处理呢

**Comment by niunai2016** [comment]
垂直居中使用flex,通知栏使用react-naigation的SafeAreaView，看我提交的App.js

**Comment by niunai2016** [comment]
> 文字会被通知栏遮挡，应该怎么处理呢
垂直居中使用flex,通知栏使用react-naigation的SafeAreaView，看我提交的App.js
