### ISSUE TITLE
建议在README代码块```之后加上js字样，代码就会高亮了。

### ISSUE THREAD

**Issue by echokk11** [niunai2016/ReactNativeAppDemo#2]
- 没加
```
const name = 'niunai2016';
```

- 加了
```js
const name = 'niunai2016';
```

**Comment by niunai2016** [comment]
> * 没加
> 
> ```
> const name = 'niunai2016';
> ```
> * 加了
> 
> ```js
> const name = 'niunai2016';
> ```

非常感谢你的建议  我试试看
